Repository optakt/optakt.github.io, pull requests merged in 2021-11, with the labels that each got.

#1 Bootstrap MkDocs
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .gitignore
  .markdownlint.json
  content/design.md
  content/index.md
  content/process.md
  content/projects.md
  content/style/go.md
  content/style/markdown.md
  content/testing.md
  mkdocs.yml
  requirements.txt
Labels: documentation, enhancement

#8 Testing guide page
  .github/workflows/ci.yml
  .markdownlint.json
  LICENSE
  README.md
  content/design.md
  content/include/generic.md
  content/include/index_internal_test.md
  content/include/mapper_new.md
  content/include/mapper_new_internal_test.md
  content/include/mapper_old.md
  content/include/mock_example.md
  content/include/mock_test_example.md
  content/include/table_driven_parallel.md
  content/process.md
  content/style/markdown.md
  content/testing.md
  mkdocs.yml
  requirements.txt
Labels: documentation

#10 Projects page
  content/projects.md
  mkdocs.yml
Labels: documentation

#11 Add Introduction page
  content/index.md
  mkdocs.yml
Labels: documentation

#9 Style guidelines
  .markdownlint.json
  content/style/go.md
  content/style/markdown.md
  content/stylesheets/wide.css
  mkdocs.yml
Labels: documentation

#13 Add Knowledge Base docs
  content/knowledge_base/flare/consensus/avalanche/concepts.md
  content/knowledge_base/flare/consensus/avalanche/specification.md
  content/knowledge_base/flare/consensus/stellar/concepts.md
  content/knowledge_base/flare/consensus/stellar/specification.md
  content/knowledge_base/flare/specification.md
  content/knowledge_base/flow/specification.md
  content/knowledge_base/glossary.md
  mkdocs.yml
Labels: documentation

#16 Flow Documentation
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .gitignore
  .markdownlint.json
  LICENSE
  content/design.md
  content/include/generic.md
  content/include/index_internal_test.md
  content/include/mapper_new.md
  content/include/mapper_new_internal_test.md
  content/include/mapper_old.md
  content/include/mock_example.md
  content/include/mock_test_example.md
  content/include/table_driven_parallel.md
  content/index.md
  content/knowledge_base/flow/cadence/accounts.md
  content/knowledge_base/flow/cadence/contracts/contracts.md
  content/knowledge_base/flow/cadence/contracts/flow_contracts.md
  content/knowledge_base/flow/cadence/introduction.md
  content/knowledge_base/flow/cadence/reference.md
  content/knowledge_base/flow/cadence/resources.md
  content/knowledge_base/flow/examples/example.md
  content/knowledge_base/flow/examples/flow-go-sdk.md
  content/knowledge_base/flow/flow_virtual_machine/case_study.md
  content/knowledge_base/flow/flow_virtual_machine/introduction.md
  content/knowledge_base/flow/flow_virtual_machine/registers.md
  content/knowledge_base/glossary.md
  content/process.md
  content/projects.md
  content/style/go.md
  content/style/markdown.md
  content/stylesheets/wide.css
  content/testing.md
  mkdocs.yml
  requirements.txt
Labels: documentation

#17 Fix documentation
  content/knowledge/cadence.md
  content/knowledge/flare.md
  content/knowledge/flow.md
  content/knowledge/glossary.md
  content/overview.md
  content/process/git.md
  mkdocs.yml
Labels: bug, documentation

#18 Update outdated guidelines about errors
  content/code/go.md
Labels: bug, documentation
